on:
  push:
    branches:
    - master

name: push image
jobs:
  dockerpush:
    name: docker build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.0.0
    - name: extract tag
      id: vars
      run: |
        echo ::set-output name=debian_version::$(grep '^FROM debian' Dockerfile  | cut -d ' ' -f 2 | cut -d ':' -f 2)
        echo "Pushing version ${{ steps.vars.outputs.debian_version }}"
    - name: Build docker image
      run: |
        export IMAGENAME="github.com/ironpeakservices/iron-debian:${{ steps.vars.outputs.debian_version }}"
        docker build --tag "$IMAGENAME" .
        docker save --output image.tar "$IMAGENAME"
    - name: Squash docker image
      run: |
        wget https://github.com/jwilder/docker-squash/releases/download/v0.2.0/docker-squash-linux-amd64-v0.2.0.tar.gz
        tar -C . -xzvf docker-squash-linux-amd64-v0.2.0.tar.gz
        sudo ./docker-squash -i image.tar -t "$IMAGENAME" -verbose | docker load
        rm image.tar
    - name: Docker Login
      uses: azure/docker-login@v1
      with:
        login-server: docker.pkg.github.com
        username: hazcod
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: docker push
      run: docker push "github.com/ironpeakservices/iron-debian:${{ steps.vars.outputs.debian_version }}"
    - name: Create GitHub release
      uses: actions/create-release@v1
      with:
          tag_name: ${{ steps.vars.outputs.debian_version }}
          release_name: iron-debian
          draft: false
          prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
